ALTER TABLE provider_data
    ADD COLUMN IF NOT EXISTS latitude DECIMAL(10,8) DEFAULT NULL AFTER province,
    ADD COLUMN IF NOT EXISTS longitude DECIMAL(11,8) DEFAULT NULL AFTER latitude,
    ADD COLUMN IF NOT EXISTS location_name VARCHAR(255) DEFAULT NULL AFTER longitude;
